import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

// Generated by plugins/artifact-workflow/scripts/build.ts and verified by check:dist.
const generatedJavaScript = new Set(['plugins/artifact-workflow/mcp/task-memory.cjs']);
const repository = fileURLToPath(new URL('../', import.meta.url));

export function checkTypeScript(root: string = repository): string[] {
  // Include unstaged additions and tracked files even if later gitignored.
  const paths = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], {
    cwd: root,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  return [...new Set(paths.split('\0'))]
    .filter(
      (path) => /\.(?:[cm]?js|jsx)$/i.test(path) && !generatedJavaScript.has(path) && existsSync(resolve(root, path)),
    )
    .sort();
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    const violations = checkTypeScript();
    if (violations.length) {
      throw new Error(`Maintained code must use TypeScript (.ts):\n${violations.join('\n')}`);
    }
    console.log('All maintained code uses TypeScript.');
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
