import { build } from 'esbuild';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const args = process.argv.slice(2);
if (args.some((arg) => arg !== '--check')) throw new Error('Usage: node scripts/build.mjs [--check]');
const check = args.includes('--check');
const result = await build({
  absWorkingDir: root,
  entryPoints: ['mcp/src/index.ts'],
  outfile: 'mcp/task-memory.cjs',
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node22.19',
  minify: true,
  legalComments: 'linked',
  metafile: true,
  write: false,
  banner: { js: '// Generated by npm run build. Source: mcp/src/. See THIRD_PARTY_LICENSES.txt.' },
});
const artifacts = new Map(result.outputFiles.map((file) => [relative(root, file.path), Buffer.from(file.contents)]));

// Ship dependencies so runtime startup never needs npm or a network connection.
const packages = new Set(
  Object.keys(result.metafile.inputs).flatMap((path) => {
    const match = path.match(/^node_modules\/((?:@[^/]+\/)?[^/]+)\//);
    return match ? [match[1]] : [];
  }),
);
const notices = [];
for (const name of [...packages].sort()) {
  const directory = new URL(`../node_modules/${name}/`, import.meta.url);
  const metadata = JSON.parse(await readFile(new URL('package.json', directory), 'utf8'));
  const licenses = (await readdir(directory)).filter((file) => /^licen[cs]e(?:\..*)?$/i.test(file));
  if (!licenses.length) throw new Error(`Missing bundled dependency license: ${name}`);
  notices.push(
    `${name} ${metadata.version} (${metadata.license})\n\n${(await Promise.all(licenses.sort().map((file) => readFile(new URL(file, directory), 'utf8')))).join('\n')}`,
  );
}
artifacts.set('mcp/THIRD_PARTY_LICENSES.txt', Buffer.from(`${notices.join('\n\n--------------------\n\n')}\n`));

// Portable manifests remain canonical; compatibility files are generated from them.
const manifest = JSON.parse(await readFile(new URL('../plugin.json', import.meta.url), 'utf8'));
const { $schema, ...identity } = manifest;
const compatibility = {
  ...identity,
  skills: './skills/',
  mcpServers: './.mcp.json',
  interface: {
    displayName: '成果物生成ワークフロー',
    shortDescription: '合意済み計画を保持して成果物を生成・検証し、完成品を引き渡す',
    longDescription: manifest.description,
    developerName: manifest.author.name,
    category: 'Productivity',
    capabilities: [],
    defaultPrompt: ['$artifact-workflow で、作成する成果物の計画から進めてください。'],
  },
};
artifacts.set('.codex-plugin/plugin.json', Buffer.from(`${JSON.stringify(compatibility, null, 2)}\n`));
const mcp = JSON.parse(await readFile(new URL('../mcp.json', import.meta.url), 'utf8'));
artifacts.set('.mcp.json', Buffer.from(`${JSON.stringify({ mcpServers: mcp.mcpServers }, null, 2)}\n`));

const outdated = [];
for (const [path, contents] of artifacts) {
  const filename = new URL(`../${path.replaceAll('\\', '/')}`, import.meta.url);
  if (check) {
    let current;
    try {
      current = await readFile(filename);
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    if (!current?.equals(contents)) outdated.push(path);
  } else {
    await mkdir(dirname(fileURLToPath(filename)), { recursive: true });
    await writeFile(filename, contents);
  }
}
if (outdated.length) {
  throw new Error(
    `Generated artifacts are missing or outdated: ${outdated.join(', ')}. Run npm run build and commit the generated files.`,
  );
}
console.log(
  check
    ? 'All shipped artifacts match the current sources; no files were changed.'
    : 'Built bundled MCP runtime, dependency licenses, and Codex compatibility manifests.',
);
