import { build } from 'esbuild';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

process.chdir(fileURLToPath(new URL('..', import.meta.url)));
const result = await build({
  entryPoints: ['mcp/src/index.ts'],
  outfile: 'mcp/task-memory.cjs',
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node22.19',
  minify: true,
  legalComments: 'linked',
  metafile: true,
  banner: { js: '// Generated by npm run build. Source: mcp/src/. See THIRD_PARTY_LICENSES.txt.' },
});

// Ship dependencies so runtime startup never needs npm or a network connection.
const packages = new Set(Object.keys(result.metafile.inputs).flatMap(path => {
  const match = path.match(/^node_modules\/((?:@[^/]+\/)?[^/]+)\//);
  return match ? [match[1]] : [];
}));
const notices = [];
for (const name of [...packages].sort()) {
  const directory = `node_modules/${name}`;
  const metadata = JSON.parse(await readFile(`${directory}/package.json`, 'utf8'));
  const licenses = (await readdir(directory)).filter(file => /^licen[cs]e(?:\..*)?$/i.test(file));
  if (!licenses.length) throw new Error(`Missing bundled dependency license: ${name}`);
  notices.push(`${name} ${metadata.version} (${metadata.license})\n\n${(await Promise.all(licenses.sort().map(file => readFile(`${directory}/${file}`, 'utf8')))).join('\n')}`);
}
await writeFile('mcp/THIRD_PARTY_LICENSES.txt', `${notices.join('\n\n--------------------\n\n')}\n`);

// Portable manifests remain canonical; compatibility files are generated from them.
const manifest = JSON.parse(await readFile('plugin.json', 'utf8'));
const { $schema, ...identity } = manifest;
await mkdir('.codex-plugin', { recursive: true });
const compatibility = {
  ...identity, skills: './skills/', mcpServers: './.mcp.json',
  interface: {
    displayName: '成果物生成ワークフロー',
    shortDescription: '合意済み計画を保持して成果物を生成・検証し、完成品を引き渡す',
    longDescription: manifest.description,
    developerName: manifest.author.name,
    category: 'Productivity',
    capabilities: [],
    defaultPrompt: ['$artifact-workflow で、作成する成果物の計画から進めてください。'],
  },
};
await writeFile('.codex-plugin/plugin.json', `${JSON.stringify(compatibility, null, 2)}\n`);
const mcp = JSON.parse(await readFile('mcp.json', 'utf8'));
await writeFile('.mcp.json', `${JSON.stringify({ mcpServers: mcp.mcpServers }, null, 2)}\n`);
console.log('Built bundled MCP runtime, dependency licenses, and Codex compatibility manifests.');
